<a href="https://colab.research.google.com/github/Sumit-Sahu90/Road-Safety-Analysis/blob/main/Day01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:

import numpy as np
import pandas as pd


np.random.seed(42) # For reproducibility
n_samples = 100 # Number of samples

data = {
    'age': np.random.randint(18, 60, size=n_samples),
    'salary': np.random.randint(30000, 120000, size=n_samples),
    'department': np.random.choice(['IT', 'HR', 'Finance', 'Marketing'], size=n_samples),
    'years_experience': np.round(np.random.normal(5, 2, size=n_samples), 1),
    'is_manager': np.random.choice([0, 1], size=n_samples)
}
df = pd.DataFrame(data)

In [2]:
df.head()

   age  salary department  years_experience  is_manager
0   56   38392         IT              -0.8           0
1   46   60535  Marketing               3.4           1
2   32  108603         HR               5.0           1
3   25   82256         HR               4.2           1
4   38  119135         HR               4.1           1

In [3]:

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 5 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   age               100 non-null    int64
 1   salary            100 non-null    int64
 2   department        100 non-null    object
 3   years_experience  100 non-null    float64
 4   is_manager        100 non-null    int64
dtypes: float64(1), int64(3), object(1)
memory usage: 4.0+ KB

In [4]:
df.describe()

              age         salary  years_experience  is_manager
count  100.000000     100.000000        100.000000  100.000000
mean    37.910000   77809.160000          4.823000    0.470000
std     12.219454   26058.643576          2.237822    0.501614
min     18.000000   30206.000000         -0.800000    0.000000
25%     26.750000   55141.000000          3.475000    0.000000
50%     38.000000   80932.000000          4.700000    0.000000
75%     46.250000   98107.250000          6.000000    1.000000
max     59.000000  119474.000000         11.400000    1.000000

In [6]:
ages = df['age'].values
salaries = df['salary'].values

ages[:5], salaries[:5]

(array([56, 46, 32, 25, 38]), array([ 38392,  60535, 108603,  82256, 119135]))

In [7]:
np.mean(salaries)

np.float64(77809.16)

In [8]:
df[df['age'] > 40]

    age  salary department  years_experience  is_manager
0    56   38392         IT              -0.8           0
1    46   60535  Marketing               3.4           1
5    56   65222    Finance               2.8           0
10   41   40965         IT               9.5           1
11   53   54538  Marketing               5.3           0
12   57  100592    Finance               6.1           1
13   41   38110         HR               2.0           1
17   41  112948  Marketing               6.7           1
18   47   36910  Marketing               7.6           0
19   55   30206    Finance               2.3           0
22   50   53419         HR               5.0           0
25   42   84268    Finance               5.8           0
26   44  117939  Marketing               1.4           0
27   59   48141  Marketing               4.5           0
28   45  110356    Finance               5.7           1
32   54   63827  Marketing               9.2           0
36   56  105450  Marketing               4.8           1
39   42   94044  Marketing               1.8           0
42   43   32693         HR               3.3           0
45   45   78925         HR               4.1           1
48   52   48047    Finance               1.4           1
51   53   45707         HR               4.0           1
52   57   51976  Marketing               3.5           0
56   59   96842         IT               1.9           1
58   46   36776         IT               2.6           1
60   43   39474         HR               5.3           0
61   51   88053  Marketing               5.3           0
63   53   35530         IT               1.2           1
65   48   43545    Finance               4.0           0
70   57   98840    Finance               3.5           0
74   41   69353  Marketing               3.3           0
75   43   92003  Marketing               6.7           0
76   42  113211         HR               8.6           0
77   58   82733  Marketing               3.6           1
78   46   95318         IT               1.9           1
81   42   97172    Finance               6.2           0
84   41   30854  Marketing               8.3           0
87   41   85680  Marketing               3.8           0
91   52   56309         HR               3.8           0
92   52  117455         IT               3.9           0
93   50   93734    Finance               7.2           0
95   59   82662         IT               4.0           0
96   56   42688         HR               4.4           1
97   58   55342  Marketing               6.0           0
98   45   67157         HR              11.4           0

In [9]:

df.iloc[:5]

   age  salary department  years_experience  is_manager
0   56   38392         IT              -0.8           0
1   46   60535  Marketing               3.4           1
2   32  108603         HR               5.0           1
3   25   82256         HR               4.2           1
4   38  119135         HR               4.1           1

In [10]:
df['bonus'] = df['salary'] * 0.10

In [11]:
df.groupby('department')['salary'].mean()

department
Finance      83124.708333
HR           73523.052632
IT           75825.476190
Marketing    77684.722222
Name: salary, dtype: float64